### ISSUE TITLE
Error when trying to add Spring Cloud Azure Starter Dependency to pom.xml

### ISSUE THREAD

**Issue by Ducanhvu** [MicrosoftDocs/azure-dev-docs#1324] opened 2023-12-30 06:29 UTC
The documentation includes a snippet to add the Spring Cloud Azure Starter dependency. However, the code snippet misses the version and causes an import error. The correct snippet is:

```
<dependency>
	<groupId>com.azure.spring</groupId>
	<artifactId>spring-cloud-azure-starter</artifactId>
	<version>4.4.0</version>
</dependency>
```

Cheers,
Duc
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2ae4dd0c-15f2-c9f3-7baf-63db0e64ce7d
* Version Independent ID: 397399cd-5129-d4b5-7f03-a01fc4c673a0
* Content: [Use Spring Data JDBC with Azure SQL Database - Java on Azure](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-sql-server?tabs=passwordless)
* Content Source: [articles/java/spring-framework/configure-spring-data-jdbc-with-azure-sql-server.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-data-jdbc-with-azure-sql-server.md)
* Service: **sql-database**
* GitHub Login: @KarlErickson
* Microsoft Alias: **judubois**

**Comment by KarlErickson** [comment] 2024-01-02 19:06
Thanks, @Ducanhvu!
@jdubois can you please validate this change? I'll update the doc after you confirm. Thanks!

**Comment by jdubois** [comment] 2024-01-03 10:35
As we import the spring-cloud-azure-dependencies BOM on the step above, you shouldn't need to specify the dependencies here.
@Ducanhvu can you share your project on GitHub, so I have a look?

**Comment by Ducanhvu** [comment] 2024-01-07 23:46
Hi @jdubois and @KarlErickson! I created a demo repo that recreates the same issue. I'm using IntelliJ Community and Maven 3.9.6 if that is relevant.
https://github.com/Ducanhvu/azuredocdemo
![image](https://github.com/MicrosoftDocs/azure-dev-docs/assets/15823001/c727f918-c2af-4af7-919a-43764725176b)
![image](https://github.com/MicrosoftDocs/azure-dev-docs/assets/15823001/983cb139-31f6-41ff-9b4e-ce7cc454ec15)

**Comment by Netyyyy** [comment] 2024-01-08 07:20
`spring-cloud-azure-dependencies` should be added into the new `dependencyManagement` tag, not the `dependencies` tag

**Comment by Netyyyy** [comment] 2024-01-09 01:04
I think the doc here https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-sql-server?tabs=passwordless#store-data-from-azure-sql-database describes the dependency, but not sure if it is clear enough?

**Comment by jdubois** [comment] 2024-01-09 11:08
OK, so we agree the documentation is correct, just that it's complicated to follow? I first want to be 100% sure there's no bug.

**Comment by KarlErickson** [comment] 2024-01-12 00:13
@jdubois @Netyyyy @Ducanhvu is the error because of the lack of a `<DependencyManagement>` element in the POM? 

If this is the cause of the error, then I think it makes sense to add a note or a sentence to clarify, since people are used to pasting dependencies into the `<dependencies>` element. Normally, documentation should indicate where to paste any given snippet, but this article just says "add the following dependencies", with the assumption that the user already knows where.

**Comment by jdubois** [comment] 2024-01-15 10:15
OK, I've written a PR that should fix this (as well as for the same content for JPA) at https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/5333 and asked @KarlErickson for review over there.

**Comment by KarlErickson** [comment] 2024-01-15 18:59
Merged. Thanks, everyone!

**Closed by KarlErickson** 2024-01-15 18:59 UTC
Labels: java, spring, doc-bug, Pri2, sql-database/svc
