### ISSUE TITLE
Problem following example -- installing ansible on the new VM

### ISSUE THREAD

**Issue by noam1023** [MicrosoftDocs/azure-dev-docs#402] opened 2021-01-19 16:53 UTC
After creating a VM using the instructions in the page, I tried the following step (installing ansible).
The process runs forever ( after 50 minutes I killed it).
I connected with ssh, found the PID of the python script and ```sudo strace -p PID``` which showed what seems like an endless loop of trying to get a file but not finding it.

Can you check?
username: cnoam@technion.ac.il
using subscription dc73146e-9f38-4018-9f2f-8e785ec4659a

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 88ac6b7d-76dc-189b-4ce7-d5f2b4043162
* Version Independent ID: 5982bd9f-1339-3a62-75a4-35161e88368e
* Content: [Quickstart - Configure Ansible using Azure CLI](https://docs.microsoft.com/en-us/azure/developer/ansible/install-on-linux-vm?tabs=ansible#install-ansible-on-an-azure-linux-virtual-machine)
* Content Source: [articles/ansible/install-on-linux-vm.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/ansible/install-on-linux-vm.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by Duffney** [comment] 2021-02-24 21:17
Hi @noam1023,

I've confirmed the issue. The `configure-ansible-centos.sh` script times out when installing Ansible because pip3 needs to be upgraded prior to installation.

I'm working on submitting a PR to fix the issue, however, in the meantime you can use the below script to configure the Linux VM and install Ansible.

Thank you for bringing this to our attention! :)

```
#!/bin/bash

# Update all packages that have available updates.
sudo yum update -y

# Install Python 3 and pip.
sudo yum install -y python3-pip

# Upgrade pip3.
sudo pip3 install --upgrade pip

# Install Ansible.
pip3 install ansible[azure]

# Install Ansible modules and plugins for interacting with Azure.
ansible-galaxy collection install azure.azcollection

# Install required modules for Ansible on Azure
wget https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt

# Install Ansible modules
sudo pip3 install -r requirements-azure.txt
```

**Comment by Duffney** [comment] 2021-02-25 15:55
Hey @noam1023,

I've updated the article, making it functional again. A PR is underway, and the article will be updated shortly. I'll go ahead and close the issue, but please let me know if you have any unanswered questions.

Thank you, again for filing the issue.

**Closed by Duffney** 2021-02-25 15:55 UTC
Labels: ansible, doc-bug
