### ISSUE TITLE
Error: runing PostgreSQL Flexible Server Database using Terraform

### ISSUE THREAD

**Issue by JCP13** [MicrosoftDocs/azure-dev-docs#765] opened 2022-04-22 21:17 UTC
Greetings, 

I have copied the sample code as explained but I get this error when I run the terraform:

│ Error: waiting for creation of the Postgresql Flexible Server "postgresqlfs-server" (Resource Group "postgresqlfs-polished-skylark"): Code="ServerGroupDropping" Message="Operations on a server group in dropping state are not allowed."
│ 
│   with azurerm_postgresql_flexible_server.default,
│   on main.tf line 74, in resource "azurerm_postgresql_flexible_server" "default":
│   74: resource "azurerm_postgresql_flexible_server" "default" {
│ 

I am not sure what this error means. I am running terraform version 1.1.9. Can you please provide some insight?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f2368d54-fdac-5b21-d467-f2e47be75061
* Version Independent ID: f2368d54-fdac-5b21-d467-f2e47be75061
* Content: [Deploy a PostgreSQL Flexible Server Database using Terraform](https://docs.microsoft.com/en-us/azure/developer/terraform/deploy-postgresql-flexible-server-database?tabs=azure-cli)
* Content Source: [articles/terraform/deploy-postgresql-flexible-server-database.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/terraform/deploy-postgresql-flexible-server-database.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment] 2023-05-10 13:10
@JCP13 This was fixed but we forgot to close the issue. Please let us know if you are still experiencing issues with the sample and we'll investigate.

**Closed by TomArcherMsft** 2023-05-10 13:10 UTC
Labels: terraform, doc-bug, terraform/svc, Pri2

**Comment by rikkigouda** [comment] 2023-06-27 04:06
Hi @TomArcherMsft - what was the root cause of this issue? We are facing the same message in Bicep. Thank you.
