### ISSUE TITLE
redhat linux doesn't use pip.  Got SSL issue after installing pip3

### ISSUE THREAD

**Issue by salavala** [MicrosoftDocs/azure-dev-docs#88] opened 2020-02-25 03:20 UTC
These instructions will NOT work for Redhat Linux. Tried to install pip27 and pip3. sudo doesn't work with pip. Don't have root permissions. I am getting ssl issue after that.

[azureuser@Oracle-Linux-HA-01 ~]$ pip3 install python-azure-sdk
pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Collecting python-azure-sdk
  Could not fetch URL https://pypi.python.org/simple/python-azure-sdk/: There was a problem confirming the ssl certificate: Can't connect to HTTPS URL because the SSL module is not available. - skipping
  Could not find a version that satisfies the requirement python-azure-sdk (from versions: )
No matching distribution found for python-azure-sdk
[azureuser@Oracle-Linux-HA-01 ~]$ wget  https://pypi.python.org/simple/python-azure-sdk/
--2020-02-25 03:14:51--  https://pypi.python.org/simple/python-azure-sdk/
Resolving pypi.python.org (pypi.python.org)... 151.101.248.223, 2a04:4e42:3b::223
Connecting to pypi.python.org (pypi.python.org)|151.101.248.223|:443... connected.
HTTP request sent, awaiting response... 301 Redirect to Primary Domain
Location: https://pypi.org/simple/python-azure-sdk/ [following]
--2020-02-25 03:14:51--  https://pypi.org/simple/python-azure-sdk/
Resolving pypi.org (pypi.org)... 151.101.192.223, 151.101.128.223, 151.101.0.223, ...
Connecting to pypi.org (pypi.org)|151.101.192.223|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-02-25 03:14:51 ERROR 404: Not Found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b440c3f1-e186-48e8-e98d-508f0d704f72
* Version Independent ID: c4dfd464-e21e-ac43-c355-d2e3f35d6f45
* Content: [Install the Azure SDK for Python](https://docs.microsoft.com/en-us/azure/python/python-sdk-azure-install#feedback)
* Content Source: [python/python-sdk-azure-install.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/python/python-sdk-azure-install.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment] 2020-02-25 18:48
@salavala Thanks for filing the issue. Does the install work if you first create and activate a virtual environment? It looks like the issue is that just running pip install attempts to install packages in the system-provided Python folder, which is likely protected, in which case using a virtual environment would be he solution.

**Comment by kraigb** [comment] 2020-03-04 00:08
@salavala Any response to my previous query?

**Comment by kraigb** [comment] 2020-03-05 18:09
Closing due to lack of a response. Please reopen if you have more details.

**Closed by kraigb** 2020-03-05 18:09 UTC
