### ISSUE TITLE
Where does APPROLE_ come from?

### ISSUE THREAD

**Issue by mrochon** [MicrosoftDocs/azure-dev-docs#997] opened 2022-12-23 16:46 UTC
My authentication is failing when I follow this article. Can you provide some info as why the authority name is APPROLE_Admin if the token contains a user role=["Admin"]? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3233e2cc-1075-1c20-d8f8-65161949e341
* Version Independent ID: e3cef834-e81c-de56-9224-a22f7abdfb7e
* Content: [How to use the Spring Boot Starter for Azure Active Directory](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory.md)
* Service: **active-directory**
* GitHub Login: @KarlErickson
* Microsoft Alias: **karler**

**Comment by KarlErickson** [comment] 2022-12-27 17:56
@chenrujun @seanli1988 can you please take a look? Thanks!

**Comment by chenrujun** [comment] 2022-12-28 01:29
Hi, @mrochon .
Thanks for reaching out.

It's an expected behavior. Here are related links:
1. Related doc: https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure?tabs=maven#authorize-access-by-app-roles
2. Related source code in web app: https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_4.5.0/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/implementation/webapp/AadOAuth2UserService.java#L162
3. Related source code in web api: https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_4.5.0/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/properties/AadResourceServerProperties.java#L35

**Comment by rajsolanki73** [comment] 2023-01-24 03:24
so as per https://stackoverflow.com/questions/72340523/why-it-is-called-approle-admin-instead-of-admin-in-spring-boot-app-secured-b i applied 

resource-server:
          claim-to-authority-prefix-map:
            roles: ""

it did not help. I also converted my yaml to properties and added spring.cloud.azure.active-directory.resource-server.claim-to-authority-prefix-map.roles="" but still granted Authorities has APPROLE_ 

I was curious how do i remove it ?

**Comment by chenrujun** [comment] 2023-01-28 08:11
Hi, @rajsolanki73 
Thanks for reaching out.

Could you please try this:

```yaml
spring:
  cloud:
    azure:
      active-directory:
        resource-server:
          claim-to-authority-prefix-map:
            scp: SCOPE_
```

**Comment by rajsolanki73** [comment] 2023-02-13 22:25
sorry for delay. Output is same. output still has Granted Authorities=[APPROLE_myrole]]] .

**Comment by chenrujun** [comment] 2023-02-14 01:36
@rajsolanki73 

There are 2 application types: web application and web api:
1. web application: support login by Azure AD account. This article mainly introduces this type: [How to use the Spring Boot Starter for Azure Active Directory](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory). In this type, `Granted Authorities=[APPROLE_Xxx]` cannot be removed. Refs: https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure_4.5.0/sdk/spring/spring-cloud-azure-autoconfigure/src/main/java/com/azure/spring/cloud/autoconfigure/aad/implementation/webapp/AadOAuth2UserService.java#L162
2. web api: Not support login, just validate access token. `spring.cloud.azure.active-directory.resource-server.claim-to-authority-prefix-map.roles` is used for this type. Here `resource-server` and `web api` have the same meaning.

In my understanding, you are using the `web application` type. So `Granted Authorities=[APPROLE_Xxx]` cannot be disabled. 

Here is my question: Why do you want to disable `Granted Authorities=[APPROLE_Xxx]`? If the reason is resonable, we will develop this feature: Disable `Granted Authorities=[APPROLE_Xxx]` in web application by a new property.

**Comment by rajsolanki73** [comment] 2023-02-14 02:21
Unless i m reading it wrong i think you are confused. 
"In my understanding, you are using the web application type. So Granted Authorities=[APPROLE_Xxx] cannot be disabled."

I dont want Granted Authorities=[APPROLE_Xxx] to be disabled. As per doc if i have setting claim-to-authority-prefix-map for roles i should be getting Granted Authorities=[Xxx] right ?

**Comment by rajsolanki73** [comment] 2023-02-14 02:24
Here is what doc says

<html><body>


spring.cloud.azure.active-directory.resource-server.claim-to-authority-prefix-map | Configure which claim will be used to build GrantedAuthority, and  prefix of the GrantedAuthority's string value. Default value is: "scp"  -> "SCOPE_", "roles" -> "APPROLE_".
-- | --



</body>
</html>

**Comment by mrochon** [comment] 2023-02-14 19:24
(For reference, [above comes from this doc](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-security-support)). Yes, my question was in the context of a web app. However, both web apps and web apis, in AAD context can get tokens with _scp_ and _roles_ claim so not sure that makes any difference. So, my understanding is: IF I want to control access to some via presence of a scp claim value, I use SCOPE_; IF it is value of roles claim then APPROLE_, but either claim is NOT expected in the claim, I must make sure NOT to use these attributes. In other words, APPROLE_ should only be there if the token/app was configured to use roles. (BTW, APPROLE sounds like 'application role', which is confusing since AAD tokens can include application and user roles, based on how the token was obtained).

**Comment by rajsolanki73** [comment] 2023-02-14 19:40
yes in my case i have configured app role which my app needs. In my app registration steps i have defined app roles as 

1) operator
2) instructor
3) speaker 

and all these values after successful authentication comes as

Granted Authorities=[APPROLE_operator]
Granted Authorities=[APPROLE_instructor]
Granted Authorities=[APPROLE_speaker ] 

All i want is to get rid of default prefix APPROLE_ and i thought following spring cloud property would do that. 

resource-server:
claim-to-authority-prefix-map:
roles: ""

**Comment by chenrujun** [comment] 2023-02-15 02:12
@mrochon , @rajsolanki73 

Here is my current understanding, correct me if I have some misunderstanding:

### Current status

1. In `web app`, the `roles` claim value in [ID token](https://learn.microsoft.com/en-us/azure/active-directory/develop/id-tokens) will be used to construct `Granted Authorities=[APPROLE_role_value]`. The prefix like `APPROLE_` **cannot** be configured.
2. In `web api`, the claims (like `roles` and `scp`) in [Access Token](https://learn.microsoft.com/en-us/azure/active-directory/develop/access-tokens) will be used to construct `Granted Authorities=[APPROLE_role_value]` and `Granted Authorities=[SCOPE_scope_value]`. The prefix like `APPROLE_` and `SCOPE_` **can** be configured by this property: `spring.cloud.azure.active-directory.resource-server.claim-to-authority-prefix-map`

### What you wanted
In `web app`, make the prefix like `APPROLE_` can be configured.

**Comment by mrochon** [comment] 2023-02-15 02:28
Yes, that looks right. Thanks for all the detail.

**Comment by chenrujun** [comment] 2023-02-15 02:40
@mrochon Thank you for the quick response.

**Comment by KarlErickson** [comment] 2023-09-11 23:47
Closing since the issue is logged elsewhere.

**Closed by KarlErickson** 2023-09-11 23:47 UTC
Labels: java, spring, product-question, active-directory/svc, Pri1
