### ISSUE TITLE
"Register a log stream handler" section is missing Python code

### ISSUE THREAD

**Issue by odscjames** [MicrosoftDocs/azure-dev-docs#1077] opened 2023-02-22 09:14 UTC
https://learn.microsoft.com/en-gb/azure/developer/python/sdk/azure-sdk-logging
"Register a log stream handler"

```
import sys
    f"Logger enabled for ERROR={logger.isEnabledFor(logging.ERROR)}, "
    f"WARNING={logger.isEnabledFor(logging.WARNING)}, "
    f"INFO={logger.isEnabledFor(logging.INFO)}, "
    f"DEBUG={logger.isEnabledFor(logging.DEBUG)}"
)
```

That's not valid Python code. It looks like a whole bunch of lines have gone missing in the middle.

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 73daacf2-462b-53ab-5d2f-8f5d42b349f8
* Version Independent ID: 73daacf2-462b-53ab-5d2f-8f5d42b349f8
* Content: [Configure logging in the Azure libraries for Python](https://learn.microsoft.com/en-gb/azure/developer/python/sdk/azure-sdk-logging)
* Content Source: [articles/python/sdk/azure-sdk-logging.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/python/sdk/azure-sdk-logging.md)
* Service: **azure-python**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by diberry** [comment] 2023-02-22 15:55
@vmagelo Can you please take a look?

**Comment by vmagelo** [comment] 2023-02-22 21:02
@odscjames - thanks for spotting that. Some bad pointers to sample files were the cause. Fix merged, should appear live later today or tomorrow.

**Comment by vmagelo** [comment] 2023-02-27 18:26
Live.

**Closed by vmagelo** 2023-02-27 18:26 UTC
Labels: python, doc-bug, Pri1, azure-python/svc
