### ISSUE TITLE
azurerm provider change

### ISSUE THREAD

**Issue by bigjon440** [MicrosoftDocs/azure-dev-docs#452] opened 2021-02-23 18:53 UTC
[Enter feedback here]
Need to change the client_id to use the sp Application (client) ID instead of the Display name. This took me over an hour of digging and researching to figure out.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d35c94ec-c9ad-0233-4115-3ddc43ddcd38
* Version Independent ID: 6b231b6b-523b-445d-2b15-7dfc04da7ef9
* Content: [Quickstart - Configure Terraform using Azure Cloud Shell](https://docs.microsoft.com/en-us/azure/developer/terraform/get-started-cloud-shell)
* Content Source: [articles/terraform/get-started-cloud-shell.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/get-started-cloud-shell.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment] 2021-02-25 19:43
@bigjon440 Apologies for the confusion. This was fixed in the documentation last week and we're waiting on a build to publish the article live. The updated doc should be live within the next day or two. I'm going to close this as a dupe of PR #444.

**Closed by TomArcherMsft** 2021-02-25 19:43 UTC
Labels: Needs: triage :mag:, terraform
