### ISSUE TITLE
mvn azure-webapp:config execution error

### ISSUE THREAD

**Issue by rThangakumar** [MicrosoftDocs/azure-dev-docs#82] opened 2020-02-13 16:49 UTC
When I execute the command 'mvn azure-webapp:config', it stops at "Define value for OS(Default: Linux):" and doesn't accept user input.

PS C:\Users\rthan\OneDrive\Documents\code\rest-service&gt; mvn azure-webapp:config
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------&lt; com.rainbowhomes:rest-service &gt;--------------------
[INFO] Building rest-service 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- azure-webapp-maven-plugin:1.9.0:config (default-cli) @ rest-service ---
[WARNING] The plugin may not work if you change the os of an existing webapp.
Define value for OS(Default: Linux): 
1. linux [*]
2. windows
3. docker

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8c8ea8c-de94-1e4b-8da3-5af1fe04c9b6
* Version Independent ID: 69c11e55-5a5e-584d-5c4b-71cea89d34da
* Content: [Deploy a Spring Boot JAR file Web App to Azure App Service on Linux](https://docs.microsoft.com/en-us/azure/java/spring-framework/deploy-spring-boot-java-app-with-maven-plugin#feedback)
* Content Source: [java/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/java/spring-framework/deploy-spring-boot-java-app-with-maven-plugin.md)
* Service: **app-service**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by rThangakumar** [comment] 2020-02-16 15:43
This was fixed when I used the command prompt. The above issue occurred when I used windows powershell.

**Comment by bmitchell287** [comment] 2020-02-24 19:12
@rThangakumar - We'll look into this. Thanks for submitting.

**Comment by KarlErickson** [comment] 2020-07-28 19:27
@rThangakumar we are unable to reproduce the problem using PowerShell, so I'm closing the issue. If you are still seeing the problem, please double-check and update your environment. If that doesn't solve it, feel free to reopen the issue and provide more information. Thanks!

**Closed by KarlErickson** 2020-07-28 19:27 UTC
Labels: spring
