### ISSUE TITLE
ridiculous documentations

### ISSUE THREAD

**Issue by hexdecimal16** [MicrosoftDocs/azure-dev-docs#747] opened 2022-04-01 15:51 UTC
I was trying to see how can I validate the jwt token that my backend recieves from frontend using azure sd b2c login protocol [Frontend = (android, angular, react) backend = (spring boot)]. After readings dozens of pages I still can't figure out how to implement it. For most parts docs just beats around the bush with repetitive functionality explained on multiple instances. Docs are not consice and to the point. Please rework on your documentations.

I am attaching AWS and Firebase docs for same functionality as they are more readable and concise:

1. See [AWS](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html)

2. See [Firebase](https://firebase.google.com/docs/auth/admin/verify-id-tokens)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f81d7cec-7853-fe76-8178-dc1fc6886f1b
* Version Independent ID: 61b1f5e0-f5cb-83c2-04ef-e8202dea9b33
* Content: [Use the Spring Boot Starter for Azure Active Directory B2C](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md)
* Service: **active-directory-b2c**
* GitHub Login: @KarlErickson
* Microsoft Alias: **edburns**

**Comment by chenrujun** [comment] 2022-11-10 02:11
#assign:@fangjian0423

**Comment by fangjian0423** [comment] 2022-11-10 09:23
@hexdecimal16 thanks for your suggestions.

We will discuss how to improve it.

**Comment by KarlErickson** [comment] 2023-09-11 23:22
Closing since the issue is logged elsewhere.

**Closed by KarlErickson** 2023-09-11 23:22 UTC
Labels: java, spring, doc-enhancement, active-directory-b2c/svc, Pri2
