### ISSUE TITLE
ERROR! couldn't resolve module/action 'azure_rm_resourcegroup'.

### ISSUE THREAD

**Issue by kamsalisbury** [MicrosoftDocs/azure-dev-docs#1316] opened 2023-12-16 13:05 UTC
Used new azure cloud shell in new subscription with no azure objects present (totally new account).
Did not pip install anything manually.
Let Azure create the new cloud shell storage account automatically.
Followed page directions exactly.
Resulted in error condition.

***
ERROR! couldn't resolve module/action 'azure_rm_resourcegroup'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/kam/create_rg.yml': line 7, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Creating resource group - "{{ name }}"
      ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes. Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"
***

Of course, the quick start page does give quoted variables.

Tried specifying the collection. collections: azure.azcollection
Tried adding possible module location to $PATH
Tried removing variables entirely.
Same result.

***
kam [ ~ ]$ ansible-playbook create_rg.yml 
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
ERROR! couldn't resolve module/action 'azure_rm_resourcegroup'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/kam/create_rg.yml': line 5, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - name: Creating resource group - ansible-lab
      ^ here
***

I researched and performed additional troubleshooting for more than an hour (that I will never get back).

Of course, ultimately, I moved on to use something else. I am not going to spend time over and over again troubleshooting what is supposed to work verbatim.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 7bf34277-7542-1451-31c7-a41aeabca49d
* Version Independent ID: b8a2871c-6ddf-4106-70f6-905684c329ef
* Content: [Get Started - Configure Ansible using Azure Cloud Shell](https://learn.microsoft.com/en-us/azure/developer/ansible/getting-started-cloud-shell?tabs=ansible)
* Content Source: [articles/ansible/getting-started-cloud-shell.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/ansible/getting-started-cloud-shell.md)
* Service: **ansible**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by ashishrajsrivastava** [comment] 2024-03-16 23:09
I just wasted my 2 hours thinking i was doing something wrong. But after loking at this issue, it seems like cloud shell itself is broken for Ansible. Ansible in Cloud shell does not work using collection or role.

**Comment by TomArcherMsft** [comment] 2024-03-27 19:59
@kamsalisbury @ashishrajsrivastava I'm working with the Ansible PM to figure out the root cause and will fix accordingly. I need to close this issue as we're moving to a new feedback system, but thanks for your contribution!

**Closed by TomArcherMsft** 2024-03-27 19:59 UTC
Labels: ansible, doc-bug, Pri2, ansible/svc
