### ISSUE TITLE
Deploy code from GitHub

### ISSUE THREAD

**Issue by Hasanofal** [MicrosoftDocs/azure-dev-docs#1249] opened 2023-09-19 13:14 UTC
I followed the tutorial and everything is working fine.

However when I try to use DefaultAzureCredential instead of AzureCliCredential, All steps are working except the last one when deploying code from GitHub repository. I get this error:
Operation returned an invalid status 'Not Found'
Content: {"Code":"NotFound","Message":"Cannot find SourceControlToken with name GitHub.","Target":null,"Details":[{"Message":"Cannot find SourceControlToken with name GitHub."},{"Code":"NotFound"},{"ErrorEntity":{"ExtendedCode":"51004","MessageTemplate":"Cannot find {0} with name {1}.","Parameters":["SourceControlToken","GitHub"],"Code":"NotFound","Message":"Cannot find SourceControlToken with name GitHub."}}],"Innererror":null}

The credential is authenticating as a service principal using a client secret with access control to the subscription with role Owner

Do I need another role with more access? because it works when I login with `az login` and use AzureCliCredential.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ded5425-f840-6dc7-ee03-8d9745bba378
* Version Independent ID: 1ded5425-f840-6dc7-ee03-8d9745bba378
* Content: [Create and deploy a Python web app to Azure App Service using the Azure SDK libraries - Python on Azure](https://learn.microsoft.com/en-us/azure/developer/python/sdk/examples/azure-sdk-example-web-app?tabs=cmd)
* Content Source: [articles/python/sdk/examples/azure-sdk-example-web-app.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/python/sdk/examples/azure-sdk-example-web-app.md)
* Service: **azure-python**
* GitHub Login: @bobtabor-msft
* Microsoft Alias: **rotabor**

**Comment by JimacoMS4** [comment] 2023-11-20 23:06
Hi @Hasanofal -- Apologies for the tardy response on this issue, we had an internal mix-up and lost track of a few issues. I've also tried this scenario using `DefaultAzureCredential` with a service principal and have also experienced problems. I had both owner and contributor roles configured at the subscription level on my service principal and still got an error. I think the issue is related to configuring the Azure service principal to authenticate with GitHub. I've reached out to our product team for help with this.

Can you let me know whether you were able to A) resolve the issue, or B) find a suitable work-around?

Thanks, and again, apologies for the delayed response, 

Jimaco

**Comment by JimacoMS4** [comment] 2023-11-20 23:10
Related to https://github.com/MicrosoftDocs/azure-dev-docs/issues/1248

**Comment by Hasanofal** [comment] 2023-11-21 07:35
Hi, thanks for your response.

I haven't found a solution yet but I managed to find a workaround. 

First, I download the code from Github as a [ZIP file](https://docs.github.com/en/free-pro-team@latest/rest/repos/contents?apiVersion=2022-11-28#download-a-repository-archive-zip) using python requests library. 

Then I deploy to Web App from the zip file using [Kudu RestAPI](https://github.com/projectkudu/kudu/wiki/Deploying-from-a-zip-file-or-url).

**Comment by JimacoMS4** [comment] 2023-11-29 08:00
@JimacoMS4 self reference for tracking

**Comment by JimacoMS4** [comment] 2023-11-29 17:39
#assign:JimacoMS4

**Comment by KarlErickson** [comment] 2023-11-29 18:00
#assign:@JimacoMS4

**Comment by JimacoMS4** [comment] 2023-12-22 21:18
Hi @Hasanofal -- I reached out to the App Service documentation team and their take is that, currently, you need to go through the portal flow to authorize App Service Build Service with your GitHub account. That would seem to exclude the use of a service principal to **set up** CI/CD on a web app. That said, you can manually set up CI/CD to use GitHub Actions with a service principal to authenticate with GitHub. This also involves making manual changes to the GH Action workflow in your repo. Once everything is set up, CI/CD will occur running under your service principal. Please see the links in my previous message for more information. 

I modified the topic to use External Git deployment rather than CI/CD. Because this form of deployment does not require any authentication or authorization with GitHub as long as it is configured against a public repo, the modified script will work when using `DefaultAzureCredential` running under both developer credentials (Azure credentials) and a service principal. Please see your other issue for details: https://github.com/MicrosoftDocs/azure-dev-docs/issues/1248. I've left that issue open for any follow up you may have. At this time, I'm going to close this issue. 

Thanks very much for your feedback. It really did lead us to making a necessary change in the topic, and it's very much appreciated.

-Jimaco

**Closed by JimacoMS4** 2023-12-22 21:18 UTC
Labels: python, doc-bug, Pri2, azure-python/svc
