### ISSUE TITLE
Needs more detail

### ISSUE THREAD

**Issue by LWarthen** [MicrosoftDocs/azure-dev-docs#710] opened 2022-02-08 12:27 UTC
Section: "Configure and compile your app"
Step 6 Configuring the yaml
1.  Where do we get the value for <your-application-ID>
2.  Do I leave "login-flow: sign-up-or-sign-in" as is or do I need to change it to some value that I should know?
3. is "logout-success-url: <your-logout-success-URL>" required? The tutorial didn't instruct to create a logout url.
4. Where do I get the value for "user-name-attribute-name: <your-user-name-attribute-name> "? I don't remember seeing that in any part of the tutorial.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f81d7cec-7853-fe76-8178-dc1fc6886f1b
* Version Independent ID: 61b1f5e0-f5cb-83c2-04ef-e8202dea9b33
* Content: [Use the Spring Boot Starter for Azure Active Directory B2C](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory-b2c-oidc.md)
* Service: **active-directory-b2c**
* GitHub Login: @KarlErickson
* Microsoft Alias: **edburns**

**Comment by chenrujun** [comment] 2022-11-04 01:20
Hi, @KarlErickson 
Could you please assign this issue to me?

**Comment by KarlErickson** [comment] 2023-09-11 23:22
Closing since the issue is logged elsewhere.

**Closed by KarlErickson** 2023-09-11 23:22 UTC
Labels: java, spring, doc-bug, active-directory-b2c/svc, Pri2
