### ISSUE TITLE
Second paragraph needs correction.

### ISSUE THREAD

**Issue by cloudysingh** [MicrosoftDocs/azure-dev-docs#567] opened 2021-07-30 16:07 UTC
In the second paragraph where it says -"By default, Terraform state is stored which isn't ideal for the following reasons:", the word --> 'locally' is missing.

The sentence should be -- "By default, Terraform state is stored locally which isn't ideal for the following reasons"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 789076a3-5d6d-e5d9-a3f7-cc1d6351ca8a
* Version Independent ID: e873b421-20fe-3415-0f4b-aacd7378c271
* Content: [Tutorial - Store Terraform state in Azure Storage](https://docs.microsoft.com/en-us/azure/developer/terraform/store-state-in-azure-storage?tabs=azure-cli)
* Content Source: [articles/terraform/store-state-in-azure-storage.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/terraform/store-state-in-azure-storage.md)
* Service: **terraform**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by TomArcherMsft** [comment] 2021-07-30 16:12
@cloudysingh Thanks for the feedback. I'm closing this as a duplicate of #561

**Closed by TomArcherMsft** 2021-07-30 16:12 UTC
Labels: Needs: triage :mag:, terraform, terraform/svc
