### ISSUE TITLE
cannot assign service principal rights to ACR

### ISSUE THREAD

**Issue by ms-zhouma** [MicrosoftDocs/azure-dev-docs#236] opened 2020-07-28 19:20 UTC
Was able to create a service principal. But getting `InvalidSchema` when assigning "Contributor" permission to it.
[Full output](https://gist.github.com/ms-zhouma/8469242bb52d1f4975ac7ccbd9a8fa56)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 15c8677e-3fcd-56c0-fa71-64d758a02ca8
* Version Independent ID: ffb63abe-0c37-4c6c-0560-3e2df33e7e5b
* Content: [Tutorial - Deploy from GitHub to Azure Kubernetes Service using Jenkins](https://docs.microsoft.com/en-us/azure/developer/jenkins/deploy-from-github-to-aks#deploy-jenkins-to-an-azure-vm)
* Content Source: [articles/jenkins/deploy-from-github-to-aks.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/jenkins/deploy-from-github-to-aks.md)
* Service: **jenkins**
* GitHub Login: @TomArcherMsft
* Microsoft Alias: **tarcher**

**Comment by Duffney** [comment] 2021-02-16 21:19
Hi @ms-zhouma,

I recently revised the articled and confirmed the syntax provided assigns the appropriate role assignment. 

The error you received indicates it might be a problem with the AzCLI version being used or the value stored in the $ACR_ID variable.

Because the syntax in the article is correct, I'll close the issue. Please reach out if your issue isn't resolved and I'll investigate.

Thank you,

**Closed by Duffney** 2021-02-16 21:19 UTC
Labels: doc-bug, jenkins
